---
when:
  - event: [pull_request, tag]
  - event: [push, manual]
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

steps:
  - name: build
    image: docker.io/goreleaser/goreleaser
    commands:
      - goreleaser build --snapshot

  - name: executable
    image: quay.io/thegeeklab/alpine-tools
    commands:
      - $(find dist/ -executable -type f -iname ${CI_REPO_NAME}_linux_amd64) --help

  - name: changelog
    image: quay.io/thegeeklab/git-sv
    commands:
      - git sv current-version
      - git sv release-notes -t ${CI_COMMIT_TAG:-next} -o CHANGELOG.md
      - cat CHANGELOG.md

  - name: publish-github
    image: docker.io/goreleaser/goreleaser
    secrets:
      - source: github_token
        target: GITHUB_TOKEN
    commands:
      - goreleaser release --release-notes=CHANGELOG.md
    when:
      - event: [tag]

depends_on:
  - docs
