---
when:
  - event: [pull_request, tag]
  - event: [push, manual]
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

steps:
  - name: testbuild
    image: docker.io/library/golang:1.22
    commands:
      - make goreleaser-snapshot
      - ls -l dist/
    when:
      - event: [pull_request, push, manual]

  - name: executable
    image: docker.io/library/golang:1.22
    commands:
      - $(find dist/ -executable -type f -iwholename *${CI_REPO_NAME}_linux_amd64*/${CI_REPO_NAME}*) --help

  - name: changelog
    image: quay.io/thegeeklab/git-sv
    commands:
      - git sv current-version
      - git sv release-notes -t ${CI_COMMIT_TAG:-next} -o CHANGELOG.md
      - cat CHANGELOG.md

  - name: publish-github
    image: docker.io/library/golang:1.22
    secrets:
      - source: github_token
        target: GITHUB_TOKEN
    commands:
      - make goreleaser-release
      - ls -l dist/
    when:
      - event: [tag]

depends_on:
  - docs
