---
when:
  - event: [pull_request, tag]
  - event: [push, manual]
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

steps:
  - name: check-unchanged
    image: docker.io/library/golang:1.22
    commands:
      - make generate
      - git diff --exit-code

  - name: markdownlint
    image: quay.io/thegeeklab/markdownlint-cli
    group: test
    commands:
      - markdownlint 'README.md' 'CONTRIBUTING.md'

  - name: spellcheck
    image: quay.io/thegeeklab/alpine-tools
    group: test
    commands:
      - spellchecker --files 'docs/**/*.md' 'README.md' 'CONTRIBUTING.md' -d .dictionary -p spell indefinite-article syntax-urls
    environment:
      FORCE_COLOR: "true"

  - name: link-validation
    image: docker.io/lycheeverse/lychee
    group: test
    commands:
      - lychee --no-progress --format detailed docs/ README.md

depends_on:
  - test
